### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ManpreetL** [jonatanYanovsky/dashboard#3]
Please look into this issue:
Screenshoot : ![error](https://user-images.githubusercontent.com/25412166/36345045-fcb75a02-13f1-11e8-9701-962703f5876d.JPG)

Code:
(myenv) manpreet@ubuntu:~/radical.entk/examples/simple_examples$ python eop.py 
2018-02-17 11:37:55,050: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
2018-02-17 11:37:55,051: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      pid: 3278
2018-02-17 11:37:55,051: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-02-17 11:37:55,108: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource Manager initialized
2018-02-17 11:37:55,109: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource description validated
2018-02-17 11:37:55,109: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
2018-02-17 11:37:55,110: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      pid: 3278
2018-02-17 11:37:55,110: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2018-02-17 11:37:55,174: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2018-02-17 11:37:55,174: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2018-02-17 11:37:55,175: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Setting up RabbitMQ system
2018-02-17 11:37:55,176: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error setting RabbitMQ system: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
2018-02-17 11:37:55,177: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 219, in run
    setup = self._setup_mqs()
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 548, in _setup_mqs
    port=self._port
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
ConnectionClosed: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused

2018-02-17 11:37:55,219: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Could not cancel resource request, error: 'NoneType' object has no attribute 'cancel'
Traceback (most recent call last):
  File "eop.py", line 101, in <module>
    appman.run()
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 457, in run
    self._resource_manager._cancel_resource_request()
  File "/home/manpreet/myenv/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 372, in _cancel_resource_request
    self._pilot.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by mturilli** [comment]
Please configure passwordless ssh access to localhost (127.0.0.1):
```
ConnectionClosed: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
```

**Comment by andre-merzky** [comment]
Hmm, I think this is not an ssh connection, but pika trying to find the RabbitMQ queues.  Guys, did you to the RabbitMQ setup part?

**Comment by vivek-bala** [comment]
Agree with Andre. Seems like RabbitMQ is not up or reachable on port 5672.

**Comment by mturilli** [comment]
Did you solve this?

**Comment by jonatanYanovsky** [comment]
We stopped developing our parser, instead we are focusing on visualization so we did not get a chance to try out these fixes.
